
spring:
  profiles:
    active: dev

---
spring:
  profiles: local

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform:
    url: jdbc:mysql://localhost:3306/whereToWatch
    username: root
    password: password
    driverClassName:


---
spring:
  profiles: dev

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform:
    url: jdbc:mysql://bf665299e38f73:0d1c73eb@us-cdbr-iron-east-02.cleardb.net/heroku_34709b4d7d7cffe?reconnect=true

    username: bf665299e38f73
    password: 0d1c73eb
    driverClassName:



